name: 'Run Scripts'

on: 
  pull_request:
    paths:
      - aws/**

defaults:
  run:
    shell: bash

jobs:
  env-vars:
    name: "check env vars"
    runs-on: ubuntu-latest
    steps:
    - name: 'print env vars'
      run: |
        echo "printing an env var"
        echo "name: ${{ vars.NAME }}"
  run-scripts:
    needs: env-vars
    name: "run local scripts"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'run scripts'
      run: | 
        ls aws
        for script in aws/*.sh; do
          if [ -f "$script" ] && [ -x "$script" ]; then
            echo "Running script: $script"
            echo bash "$script"
            bash "$script"
          fi
        done
        echo "end"

